name: Verification du Projet Book

on: [push]

jobs:
    verification-basique:
        runs-on: ubuntu-latest

        steps:
            - name: Recuperer le code
              uses: actions/checkout@v4

            - name: Installation de php
              uses:  shivammathur/setup-php@v2
              with:
                php-version: '8.2.12'

            - name: Verifier l'installation
              run: composer install --no-scripts